language: python
python:
    - "3.9"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "python manage.py test && flake8"

env:
    - DB_NAME=travis DB_USER=travis DB_HOST=db DB_PASS=travis SECRET_KEY=travis DEBUG=True